version: "3.7"
services:
  adminservice:
    image: "jonyrider/serviceadmin:0.0.3"
    restart: always
    container_name: serviceadmin
    labels:
      - name_service=serviceadmin
    ports:
        - "8000:8000"
    volumes:
        - ./config.yml:/app/config.yml
        - ./temp:/app/temp/
